apiVersion: v1
kind: ConfigMap
metadata:
  name: config-api-config
data:
  spring.json: |
    {
      "spring": {
        "cloud": {
          "config": {
            "server": {
              "git": {
                "uri": "https://github.com/lhysin/std-terraform",
                "searchPaths" : "multi-eks/example-app/spring-cloud-config",
                "username": "",
                "password": "",
                "skip-ssl-validation": true,
                "force-pull": true,
                "default-label": "main"
              }
            }
          }
        }
      }
    }