apiVersion: v1
kind: ConfigMap
metadata:
  name: config-api-config
data:
  config.json: >
    {
      "spring": {
        "cloud": {
          "config": {
            "server": {
              "git": {
                "uri": "https://",
                "username": "-",
                "password": "-",
                "skip-ssl-validation": true,
                "force-pull": true,
                "default-label": "master"
              }
            }
          }
        }
      }
    }