apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-api
  labels:
    app: config-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-api
  template:
    metadata:
      labels:
        app: config-api
    spec:
      containers:
        - name: config-api
          image: 627500151784.dkr.ecr.ap-northeast-2.amazonaws.com/cjo-std-ecr-ontrust:config-api
          ports:
            - containerPort: 8088
          env:
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: config-api-config
                  key: config.json