apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-api
  labels:
    app: bff-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bff-api
  template:
    metadata:
      labels:
        app: bff-api
    spec:
      containers:
        - name: bff-api
          image: 627500151784.dkr.ecr.ap-northeast-2.amazonaws.com/cjo-std-ecr-ontrust:bff-api
          ports:
            - containerPort: 8080