apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  config.json: >
    {
      "spring": {
        "application": {
          "name": "test-api"
        },
        "profiles": {
          "active": "dev"
        },
        "config": {
          "import": "configserver:https://www.naver.com"
        },
        "cloud": {
          "config": {
            "label": "main"
          }
        }
      }
    }