spring:
  cloud:
    gateway:

      httpclient:
        connect-timeout: 2_000
        response-timeout: 5s
        compression: true
        #max-header-size:
        #max-initial-line-length:
        pool:
          max-connections: 200
          max-idle-time: 5s
          max-life-time: 5s

      routes:
        - id: or-pay-svc
          uri: http://or-pay-svc.ontrust.svc.cluster.local
          predicates:
            - Path=/or-pay-svc/**
          filters:
            - RewritePath= /(?<path>.*), /$\{path}
          #           - RemoveRequestHeader=Authorization
          metadata: # route 별 timeout 설정(ms)
            connect-timeout: 2000
            response-timeout: 5000

        - id: or-spp-svc
          uri: http://or-spp-svc.ontrust.svc.cluster.local
          predicates:
            - Path=/or-spp-svc/**
          filters:
            - RewritePath= /(?<path>.*), /$\{path}
          #           - RemoveRequestHeader=Authorization
          metadata: # route 별 timeout 설정(ms)
            connect-timeout: 2000
            response-timeout: 5000

        - id: or-cst-svc
          uri: http://or-cst-svc.ontrust.svc.cluster.local
          predicates:
            - Path=/or-pay-svc/**
          filters:
            - RewritePath= /(?<path>.*), /$\{path}
            #            - RemoveRequestHeader=Authorization
            - name : Retry #재시도 설정 필터
              args:
                retries: 2
                statuses: BAD_GATEWAY
                methods: GET, POST
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 1000ms
                  factor: 2
                  basedOnPreviousValue: false

          metadata: # route 별 timeout 설정(ms)
            connect-timeout: 2000
            response-timeout: 1000
