apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-api
  labels:
    app: bff-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-api
  template:
    metadata:
      labels:
        app: bff-api
    spec:
      containers:
        - name: bff-api
          image: 627500151784.dkr.ecr.ap-northeast-2.amazonaws.com/cjo-std-ecr-ontrust:bff-api
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "file:/app/config/route-config.yml"  # 환경변수로 경로 전달
          volumeMounts:
            - name: config-volume
              mountPath: /app/config  # 컨테이너 내부 경로
              subPath: route-config.yml  # ConfigMap 내 파일을 해당 경로에 매핑
      volumes:
        - name: config-volume
          configMap:
            name: bff-api-config  # 사용할 ConfigMap의 이름