spring:
  cloud:
    gateway:

      httpclient:
        connect-timeout: 2_000
        response-timeout: 5s
        compression: true
        #max-header-size:
        #max-initial-line-length:
        pool:
          max-connections: 200
          max-idle-time: 5s
          max-life-time: 5s

      routes:
        - id: a-service
          uri: https://demo2409875.mockable.io
          predicates:
            - Path=/a-service/v2/**
          filters:
            - RewritePath= /a-service/(?<path>.*), /$\{path}
          #           - RemoveRequestHeader=Authorization
          metadata: # route 별 timeout 설정(ms)
            connect-timeout: 2000
            response-timeout: 5000

        - id: b-service
          uri: https://demo2409875.mockable.io
          predicates:
            - Path=/b-service/v2/**
          filters:
            - RewritePath= /b-service/(?<path>.*), /$\{path}
            #            - RemoveRequestHeader=Authorization
            - name : Retry #재시도 설정 필터
              args:
                retries: 2
                statuses: BAD_GATEWAY
                methods: GET, POST
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 1000ms
                  factor: 2
                  basedOnPreviousValue: false

          metadata: # route 별 timeout 설정(ms)
            connect-timeout: 2000
            response-timeout: 1000
